name: Build Mac app
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install pyinstaller
      - run: pyinstaller --onefile --windowed --target-architecture universal2 macapptest.py
      - uses: actions/upload-artifact@v4
        with:
          name: mac-app
          path: dist/

      - name: Package release folder
        run: |
          mkdir release_folder
          cp -r "dist/macapptest.app" release_folder/
          cp macapptest.py release_folder/
          cd release_folder
          zip -r ../dist/macapptest.zip .
      - uses: actions/upload-artifact@v4
        with:
          name: mac-zip
          path: dist/macapptest.zip
